apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.service.expose: '{{ .Values.DNS_NAME }}'
    kompose.service.type: nodeport
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  rules:
    - host: '{{ .Values.DNS_NAME }}'
      http:
        paths:
          - backend:
              serviceName: api-gateway
              servicePort: 8080
status:
  loadBalancer: {}
