apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
<<<<<<< HEAD
    kompose.version: 1.22.0 (955b78124)
=======
    kompose.version: 1.26.1 (a9d05d509)
>>>>>>> feature/msp-24
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql-server
status:
  loadBalancer: {}
