apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
<<<<<<< HEAD
    kompose.version: 1.22.0 (955b78124)
=======
    kompose.version: 1.26.1 (a9d05d509)
>>>>>>> feature/msp-24
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-server
  name: prometheus-server
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9090
  selector:
    io.kompose.service: prometheus-server
status:
  loadBalancer: {}
